tasks/apt.yml

References #6 . Creating new PR because made some mistake while sqaushing.

Add support for Debian 9

---

defaults/main.yml
templates/nginx.j2

I added a new nginx server option for http2 in nginx template and configuration option in defaults/main.yml
The default setting is false

added nginx http2 config option; default: false

---

README.md

Adds gitter shield in README.md

Added gitter shield in README.md

---

README.md
defaults/main.yml
tasks/pip.yml
templates/openwisp2/settings.py
templates/openwisp2/urls.py

Add optional network topology module

---

defaults/main.yml
tasks/cron.yml
tasks/main.yml

[WIP] Added cron to run update_topology command

---

defaults/main.yml
tasks/cron.yml

[topology] Added cron to run save_snapshot command

---

tasks/complete.yml
tasks/main.yml

add a `complete.yml` file to print messages to the user on playbook completion, e.g.
- reminding the user to the change the admin password from the link

add message on playbook completion

---

tasks/complete.yml

fix for superuser password hint in tasks/complete.yml throwing an error

Password hint fix

---

templates/uwsgi.ini.j2

Added uid option in uwsgi.ini.j2

---

tasks/cron.yml
tasks/main.yml

GCI Task: https://codein.withgoogle.com/dashboard/task-instances/4711738698104832/

[django] Automatically add the clearsessions command to crontab #24.

---

tasks/complete.yml

GCI Task: https://codein.withgoogle.com/dashboard/task-instances/6620024611536896/

[install] Show admin password warning only when superuser is first created #42.

---

README.md
defaults/main.yml
templates/openwisp2/settings.py

GCI Task: https://codein.withgoogle.com/dashboard/task-instances/6204080517021696/

Automatically configure DEFAULT_FROM_EMAIL #37

---

README.md
defaults/main.yml
tasks/apt.yml
tasks/django.yml
tasks/pip.yml
tasks/supervisor.yml
tasks/yum.yml
templates/nginx.j2
templates/openwisp2/asgi.py
templates/openwisp2/settings.py
templates/supervisor/daphne.j2
templates/supervisor/runworker.j2

@moonwolf-github could you tell me if the name of the packages for RedHat/Fedora are correct?

[gis] Added gis module + websockets

---

README.md

Fix guide on local installation

---

README.md
defaults/main.yml
tasks/apt.yml
templates/openwisp2/settings.py

Fix spatialite bug

---

README.md

Updated README for ansible minimum version

---

README.md

The instructions for local installation of OpenWISP2 using VirtualBox have been added.
References #51.

Improved local-installation documentation

---

.gitlab-ci.yml
.travis.yml
README.md
defaults/main.yml
handlers/main.yml
meta/main.yml
tasks/apt.yml
tasks/cron.yml
tasks/django.yml
tasks/django_secret_key.yml
tasks/firewalld.yml
tasks/main.yml
tasks/pip.yml
tasks/selinux.yml
tasks/yum.yml
tests/requirements.yml
tests/test.yml
tests/test_networktopology.yml

Created ci-test files to automatic test ansible role on travi-ci and gitlab.
Made minor change on ansible-playbook.

Ci testing

---

.gitignore
.gitlab-ci.yml
.travis.yml
tests/test.yml
tests/test_networktopology.yml

Set improvement on testing pipeline.
Closes #89

Improved testing pipeline #89

---

.gitlab-ci.yml
.travis.yml
tests/runtests.sh

Added a script accessed by both travis and gitlab-ci to run
openwisp and test it
Closes #84

[ci] Avoiding duplication of basic test by a script #84

---

.gitlab-ci.yml
tests/requirements.yml
tests/test.yml
tests/test_networktopology.yml

[qa] Fixed travis build on PR and asible-lint job in gitlab-ci

---

.gitlab-ci.yml
.travis.yml
handlers/main.yml
tasks/apt.yml
tasks/yum.yml
tests/runtests.sh

Ensure redis is running after installation and added CI test for it!
Fixes #94

[bug] ensure redis service has started and is running #94

---

tests/runtests.sh

If we fix #103 we should see these tests failing (if the syntax is correct).

[tests] Run a subset of django tests

---

README.md

Updated README.md for Developer Environment Setup with step installation #92

[docs] Added development install instructions #92

---

tests/runtests.sh

Added a short description about what is going to happen in each test.
Fixes #108

Fixed output of runtests.sh #108

---

.travis.yml

Added commit message style check

[qa] Added commit message style check

---

.ansible-lint
.travis.yml
tasks/apt.yml
tasks/firewalld.yml
tasks/multitenancy_migration.yml
tasks/nginx.yml
tasks/pip.yml
tasks/supervisor.yml
tasks/variables-spatialite.yml
tasks/yum.yml
tests/test.yml
tests/test_networktopology.yml

Add ansible linter and fix Trailing whitespace.
Fixes #19

[qa] Add ansible linter to build #91

---

.ansible-lint
tasks/apt.yml
tasks/django.yml
tasks/multitenancy_migration.yml
tasks/pip.yml
tasks/yum.yml

I've been seeing some odd errors on Ansible recently and some new `ansible-lint` warnings popped up since the last PR. Hopefully, this solves all of them and builds can pass again.
For example: [Travis CI](https://travis-ci.org/openwisp/ansible-openwisp2/jobs/496595884#L621)

[ci] resolve ansible-lint errors

---

README.md
defaults/main.yml
tasks/pip.yml

This one was missing in the ansible role.

[pip] Add openwisp2_utils_pip variable

---

tasks/pip.yml

@okraits I bumped into the same issue you had.

[pip] Updated when syntax

---

.gitlab-ci.yml
.travis.yml
handlers/main.yml
meta/main.yml
tasks/apt.yml
tests/runtests.sh

We'r dropping support for Debian 8 from this ansible role.

[general] Dropped support for debian 8

---

README.md

This PR adds section to README about deploying
project on docker container.
Fixes #152

[README] Added README section about deploying docker #152

---

README.md

Changed the path to indicate the update from VirtualBox 5.2.0 onwards
Also added a few small wording changes to improve understanding.
Fixes #148

[docs] Update the Host-Only Network location for VM #148

---

README.md
defaults/main.yml
tasks/django.yml
tasks/pip.yml
tasks/supervisor.yml
templates/celery.j2
templates/openwisp2/__init__.py
templates/openwisp2/celery.py
templates/openwisp2/settings.py

Added support for the connections module and celery.
Closes #153

[controller] Add support for connections module (celery) #153

---

README.md

Signed-off-by: Nicholas Smith <mips171@icloud.com>
Closes #102.

[README] Add basic system requirements

---

tasks/pip.yml

Merge this once the new version of django-netjsonconfig and openwisp-controller are out.

[pip] Ensure jsonfield2 package is removed

---

README.md
defaults/main.yml
tasks/pip.yml
templates/celery.j2
templates/openwisp2/__init__.py
templates/openwisp2/celery.py

Various minor improvements due to problems found out during latest deployments of new bleeding edge features.

Various minor improvements

---

tasks/pip.yml

[pip] Ensure attrs python package is latest

---

.travis.yml

Switched to openwisp-utils 0.5

[ci] Switched to openwisp-utils 0.5

---

README.md
defaults/main.yml
templates/nginx.j2
templates/openwisp2/celery.py
templates/openwisp2/settings.py

Improved logging

---

tasks/pip.yml

Skipped idempotence tests for
- "Install custom OpenWISP 2 Python packages" task
Fixes #218

[fix] Skipped idempotence test #218

---

templates/openwisp2/settings.py

[fix] Fix email confirmation

---

README.md
defaults/main.yml
tasks/pip.yml
templates/openwisp2/settings.py

Manually tested by creating a device! :smile:
Closes #184

[gsoc2020] Remove django-netjsonconfig #184

---

defaults/main.yml
molecule/resources/verify.yml
tasks/pip.yml
templates/openwisp2/settings.py

`flat_json_widget` is now added to INSTALLED_APPS in the settings.py
Closes #197
------------------
**Blockers**

[deps] Added support for openwisp-controller 0.8.0

---

molecule/resources/converge.yml
tasks/pip.yml
templates/openwisp2/settings.py

Closes #216
-------------
**Blockers**
- Requires new releases of 
----------
I have used the following playbook to test the role on Ubuntu 20.04 
```yaml
- hosts: openwisp2
become: "{{ become | default('yes') }}"
roles:
- openwisp.openwisp2
vars:
openwisp2_default_from_email: "openwisp2@openwisp2.mydomain.com"
openwisp2_controller_pip: https://github.com/openwisp/openwisp-controller/tarball/master
openwisp2_users_pip: https://github.com/openwisp/openwisp-users/tarball/master
openwisp2_utils_pip: https://github.com/openwisp/openwisp-utils/tarball/master
openwisp2_django_netjsonconfig_pip: https://github.com/openwisp/django-netjsonconfig/tarball/master
openwisp2_django_x509_pip: https://github.com/openwisp/django-x509/tarball/master
openwisp2_netjsonconfig_pip: …
```

[feature] Added static files minification and cache invalidation #216

---

.github/workflows/ci.yml
README.md
defaults/main.yml
handlers/main.yml
meta/main.yml
molecule/default/molecule.yml
molecule/local/molecule.yml
molecule/resources/verify.yml
tasks/apt.yml
tasks/complete.yml
tasks/django.yml
tasks/django_secret_key.yml
tasks/main.yml
tasks/nginx.yml
tasks/pip.yml
tasks/ssh.yml
tasks/supervisor.yml
tasks/variables-spatialite.yml
tasks/variables.yml
vars/main.yml

** Still working on this, just tied up with other work! :smile:

[minor] Fixed GitHub unchanged files with check annotations

---

templates/openwisp2/settings.py
templates/openwisp2/urls.py

[feature] Add API URLs by default #234

---

tasks/django.yml
tasks/pip.yml

[change] Removed public read permission

---

README.md
defaults/main.yml
meta/main.yml
tasks/apt.yml
tasks/nginx.yml
tasks/pip.yml
tasks/variables.yml
templates/openwisp2/settings.py

Allow disabling postfix and redis in case these services are deployed on different servers.

[misc] Allow disabling install of some dependencies

---

README.md
defaults/main.yml
templates/openwisp2/settings.py
templates/openwisp2/urls.py

Added possibility to disable controller URLs and socialaccount app.

[feature] Added possibility to disable controller URLs and socialaccount app

---

.github/workflows/ci.yml

[ci] Update imports on ansible only on builds on master branch #248

---

tasks/pip.yml

[fix] Disabled pep517 on Ubuntu 18.04 #263

---

files/logrotate.d/openwisp-nginx
tasks/apt.yml
tasks/nginx.yml

[fix] Added logrotate configuration for nginx logs #277

---

README.md

I've documented useful commands an locations

[docs] Useful commands and locations

---

README.md
defaults/main.yml
tasks/supervisor.yml
templates/openwisp2/settings.py
templates/supervisor/celery_firmware_upgrader.j2

[change] Added dedicated celery queue for firmware upgrader #273

---

tasks/supervisor.yml

[fix] Add firmware-upgrader celery worker only when module is used #297

---

README.md

[docs] Added instructions for using dev branch #300 

---

README.md

Recommended installing ansible via a virtual environment and added a note about `jinja2`
Should close #311

[docs] Added virtual env note in ansible installation #311

---

README.md

[docs] Fix autoscale comments in README #302

---

handlers/main.yml
tasks/apt.yml
templates/supervisor/celerybeat.j2

- celerybeat-schedule.db will be removed whenever there's a
change to python code
- Added "python3-gdbm" system package
- Related to https://github.com/openwisp/openwisp-monitoring/issues/325

[change] Added handler for removing celerybeat-schedule.db

---

.github/workflows/ci.yml
README.md
defaults/main.yml
handlers/main.yml
meta/main.yml
molecule/resources/converge.yml
molecule/resources/requirements.yml
molecule/resources/verify.yml
tasks/apt.yml
tasks/django.yml
tasks/freeradius.yml
tasks/main.yml
tasks/nginx.yml
tasks/pip.yml
tasks/supervisor.yml
templates/freeradius/daily-bandwidth-counter/mysql.j2
templates/freeradius/daily-bandwidth-counter/postgresql.j2
templates/freeradius/daily-bandwidth-counter/sqlite.j2
templates/freeradius/daily-counter/postgresql.j2
templates/freeradius/inner_tunnel.j2
templates/freeradius/monthly-counter/postgresql.j2
templates/freeradius/openwisp_site.j2
templates/freeradius/rest.j2
templates/freeradius/sql.j2
templates/freeradius/sql_counter.j2
templates/openwisp2/settings.py
templates/openwisp2/urls.py
templates/supervisor/celery_monitoring.j2

- Adds support for internationalization

[feature] Adds openwisp-monitoring, openwisp-radius and bug fixes. 

---

README.md
tasks/django.yml
templates/openwisp2/settings.py

[change] Added option to upload custom static files #322

---

README.md
tasks/django.yml
tasks/pip.yml
templates/openwisp2/settings.py

[change] Renamed custom static directory to ow2_static #322

---

templates/supervisor/celery.j2
templates/supervisor/celery_firmware_upgrader.j2
templates/supervisor/celery_monitoring.j2
templates/supervisor/celery_network.j2

[fix] Updated celery supervisor config to support Celery 5 #327

---

tasks/apt.yml
tasks/pip.yml

- Role will install Python 3.7 if Python version < 3.7 is found.
- Pinned setuptools~=59.6.0

[fix] Fixed support for Ubuntu 18.04

---

README.md
defaults/main.yml
molecule/resources/converge.yml
molecule/resources/verify.yml
templates/openwisp2/settings.py

- openwisp-ipam will be installed and enabled by default.
Closes #334
**Blockers**
- https://github.com/openwisp/openwisp-controller/pull/591

[feature] Added support for openwisp_controller.subnet_division #334

---

README.md
defaults/main.yml
templates/openwisp2/settings.py

[feature] Added sesame default configuration #331

---

README.md
defaults/main.yml
tasks/nginx.yml
templates/nginx/security-conf.j2
templates/nginx/site-conf.j2
templates/nginx/ssl-conf.j2

- Dropped TLSv1.0 and TLSv1.1 protocol
- Updated cipher list
Closes #339
Closes #340 
Closes #341

[change] Updated nginx ssl configuration #339

---

templates/uwsgi.ini.j2

[fix] Fixed uwsgi OSerror #343

---

templates/logrotate.d/openwisp-nginx.j2

Use "rotate" instead of "reload" in postrotate script

[chores] Updated nginx logrotate configuration

---

tasks/nginx.yml

Added task in `nginx.yml`, which sets the `server_tokens` to `off`
Closes #353
Successfully build : https://github.com/Aryamanz29/ansible-openwisp2/actions/runs/1935569843

[change] Disabled nginx server_tokens #353

---

README.md
defaults/main.yml
tasks/pip.yml
templates/openwisp2/settings.py

Use django-celery email as default email backend #271

---

molecule/resources/verify.yml

[enhancement] Run tests of openwisp-notifications #227

---

templates/openwisp2/settings.py

Needed for https://github.com/openwisp/openwisp-radius/pull/394

[change] Added django.contrib.humanize

---

README.md
defaults/main.yml
tasks/pip.yml

[enhancement] Allow users to specify Django version #313

---

README.md
defaults/main.yml
templates/uwsgi.ini.j2

[feature] Added uwsgi listen option #363

---

molecule/resources/converge.yml
molecule/resources/verify.yml

Let's keep it simple or we will never release OpenWISP 22.

[ci] Removed geo api tests

---

defaults/main.yml
tasks/freeradius.yml

[fix] Install freeradius from network radius packages #368

---

README.md
defaults/main.yml
handlers/main.yml
tasks/pip.yml
templates/openwisp2/settings.py

Related to https://github.com/openwisp/openwisp-monitoring/pull/368

[chores] Added task to trigger timeseries database migration 

---

.github/workflows/ci.yml
README.md
defaults/main.yml
meta/main.yml
molecule/local/molecule.yml
tasks/freeradius.yml

~~Depends on : https://github.com/openwisp/ansible-ow-influxdb/pull/10~~
Closes #376

[feature] Added support for Ubuntu 22 #376

---

README.md
defaults/main.yml
tasks/django.yml

[change] Added geocoding check #310

---

README.md
defaults/main.yml
tasks/pip.yml
templates/openwisp2/settings.py

-  Added support for `django-cors-headers`.
-  Updated `README`.
Closes #69

[feature] Added support for django CORS #69

---

README.md
defaults/main.yml

Default openwisp2_radius_cleanup_stale_radacct to 1.

[change] Default openwisp2_radius_cleanup_stale_radacct to 1

---

README.md
defaults/main.yml
handlers/main.yml
tasks/django.yml
tasks/pip.yml
tasks/supervisor.yml
vars/main.yml

[fix] Implemeted efficient reloading of supervisor services #365

---

defaults/main.yml
tasks/freeradius.yml

[change] Use freeradius 3.2 on Ubuntu 22.04 #401

---

README.md
defaults/main.yml
molecule/resources/converge.yml
templates/uwsgi.ini.j2

Added "openwisp2_uwsgi_extra_conf" variable which allows appeding extra configuration for uwsgi in uwsgi.ini

[feature] Added ansible variable to allow configuring uwsgi parameters

---

README.md
defaults/main.yml
templates/openwisp2/settings.py

[feature] Added default EMAIL_TIMEOUT #411

---

README.md
defaults/main.yml

Set good defaults for `openwisp2_uwsgi_extra_conf`.

[change] Set good defaults for openwisp2_uwsgi_extra_conf

---

.github/workflows/ci.yml
README.md
defaults/main.yml
molecule/resources/verify.yml
tasks/pip.yml
templates/openwisp2/settings.py

[change] Updated role to install development version of OpenWSIP modules #433

---

tasks/ssh.yml

Related to https://github.com/openwisp/openwisp-controller/issues/709
-------------------------
**Blockers**

[change] Use ED25519 algorithm to generate SSH keys

---

README.md
defaults/main.yml
templates/openwisp2/settings.py

[feature] Added password expiration settings and celery task #449

---

README.md
defaults/main.yml
templates/openwisp2/settings.py

Related to https://github.com/openwisp/openwisp-radius/pull/502
Closes #463

[change!] Renamed delete_old_users to delete_old_radiusbatch_users #463

---

templates/openwisp2/__init__.py
templates/openwisp2/settings.py

This is needed due to the changes introduced in https://github.com/openwisp/openwisp-utils/pull/378.

[change] Updated logic for metric collection

---

.github/workflows/ci.yml
README.md
molecule/default/molecule.yml
molecule/local/molecule.yml
tasks/apt.yml
tasks/freeradius.yml
tasks/pip.yml

[feature] Added support for Debian 12 and Ubuntu 24

---

tasks/freeradius.yml

Perform checksum check when installing GPG keys.

[chores] Perform checksum check when installing GPG keys

---

.github/workflows/ci.yml
CONTRIBUTING.rst
pyproject.toml
run-qa-checks

Added run-qa-checks script + minor QA fixes.

[qa] Added run-qa-checks script + minor QA fixes

---

templates/openwisp2/settings.py

[chores] Added allauth.account.middleware.AccountMiddleware

---

docs/user/enabling-modules.rst

Required for https://github.com/openwisp/openwisp-docs/pull/206

[docs] Fixed RADIUS module reference

---

tasks/freeradius.yml

[chores] Don't upgrade all packages while installing FreeRADIUS

---

defaults/main.yml
templates/openwisp2/settings.py

Closes #500
Updated "openwisp2_radius_delete_old_radiusbatch_users" to set number of days instead of number of months.

[change!] Updated openwisp2_radius_delete_old_radiusbatch_users #500

---

defaults/main.yml
handlers/main.yml

[deps] Upgraded OpenWISP modules to latest stable version

---

tasks/pip.yml

[deps] Upgraded deploy dependencies

---

CHANGES.md
templates/openwisp2/__init__.py

24.11.1 release

---

CHANGES.md

[docs] Fixed missing OpenWISP RADIUS upgrade in 24.11.0 changelog

---

tasks/pip.yml

- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A I have updated the documentation.

[chores] Removed old maintenance jsonfield2 removal task

---

files/generate_django_secret_key.py
templates/load_initial_data.py
templates/openwisp2/__init__.py
templates/openwisp2/celery.py
templates/openwisp2/routing.py
templates/openwisp2/settings.py
templates/openwisp2/urls.py
templates/openwisp2/version.py

- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A I have updated the documentation.

[qa] Switched to double quotes (black formatter)
