- README.md
The word 'may' was spelled as 'ma'.
> Misspelled word on line no. 290

- README.md
1) The `--ask-sudo-pass` argument will not need the sshpass program. Any ssh connection with password will need sshpass program
Proof: ansible-playbook -i hosts playbook.yml -u artem -k
...
fatal: [192.168.1.15]: FAILED! => {"msg": "to use the 'ssh' connection type with passwords, you must install the sshpass program"}
(there no `--ask-sudo-pass` argument)
2) The `--ask-sudo-pass` is "deprecated, use become", so replace it to become :)
3) I had problem "Authentication or permission failure" so using root access (login) directly fixed it
> Improved installation guide a bit

- defaults/main.yml
- tasks/apt.yml
- tasks/main.yml
- tasks/python_update.yml
- vars/main.yml
Adds task python_update to install python3.6.3 from its deb packages. Set variable `openwisp2_python_update` to `true` to run the task.
Fixes #61
> [python_update] Adds task to update to python3.6

- defaults/main.yml
- templates/openwisp2/settings.py
Made changes to settings.py in templates/openwisp2 from the references mentioned to enable djnago templating using django redis
Fixes Issue #78
> [django_cache] Adds cache templating settings #78

- tasks/apt.yml
- tasks/yum.yml
This package shouldn't be installed when using another DB
eg: PostgreSQL with the Postgis extension.
> [pkg] Install libsqlite3-mod-spatialite only when needed

- .gitlab-ci.yml
- .travis.yml
- README.md
- defaults/main.yml
- tasks/apt.yml
- tasks/main.yml
- tasks/variables-spatialite.yml
- tasks/yum.yml
- `openwisp2_spatialite_path` value changes according to `ansible_distribution` & `ansible_distribution_version`
- added `.travis.yml` & `.gitlab-ci.yml` jobs for `debian 10` and `ubuntu 18.04`
Fixes #77
> [variables][Fixes #77] Spatialite Path Changes According to OS

- tasks/pip.yml
If the upgrade of the dependencies is triggered, not yet compatible
version of django may be installed breaking the openwisp2 instance.
#103 and #105 should be addressed before merging this PR.
> [pip] Install django-redis without triggering dependencies upgrade

- README.md
- meta/main.yml
- tasks/apt.yml
- tasks/pip.yml
The deprecation warnings referenced in the issue are not present anymore, but there were other warnings, which I fixed.
Ansible gives deprecation warnings for the "apt" and "pip" tasks. For example: 
```
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of
using a loop to supply multiple items and specifying `name: {{ item }}`, please use `name: ['sudo', 'software-
properties-common', 'build-essential', 'supervisor', 'nginx', 'openssl', 'libssl-dev', 'libffi-dev', 'python-dev',
'redis-server']` and remove the loop. This feature will be removed in version 2.11. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg
```
Now, the log is free of any deprecation warnings.
Tests run using …
> [apt + pip] Fix Ansible deprecation warnings #86

- README.md
`openwisp2_extra_django_settings` is a dictionary, not a list - see https://github.com/openwisp/ansible-openwisp2/blob/master/defaults/main.yml#L13.
> [docs] Fix role variables example

- .travis.yml
- README.md
- meta/main.yml
- tasks/apt.yml
- tasks/pip.yml
- tasks/variables-spatialite.yml
- tasks/yum.yml
- tests/runtests.sh
Travis CI builds for Debian 9, Debian 10, and Fedora 28 have been fixed. 
- Python3 is set as the `ansible_python_interpreter` for Fedora 28 because it drops support for `python-firewall` which is for Python2. 
- Cron is also added to `apt.yml` to resolve errors in Debian 10. 
- Additionally, `cryptography` from pip is installed to fix an odd SSL error when installing `django-redis` on Debian 9.
- The `spatialite_path` is updated for Fedora 28
> [qa] Fix Travis CI build errors #93

- meta/main.yml
As per the .travis.yml build matrix some
new platforms were added and older one
were removed
Fixes #127
> [meta/main.yml] Added new platform #127

- .gitlab-ci.yml
- .travis.yml
- meta/main.yml
We don't have the resources now to maintain these Linux distributions.
> [ci] Disable Centos and Fedora

- tasks/nginx.yml
- templates/nginx.j2
- A new, default Nginx server block that returns 404 is added for requests that do not match accepted hostnames
- The symlink at `/etc/nginx/sites-enabled/default` is removed to disable the default Nginx configuration, so there is only one `default_server` defined per port
Closes #135
> [nginx] Add a default server block that returns 404

- tasks/pip.yml
- tests/runtests.sh
- The deprecation warning from Ansible in the `Install extra python packages` task is fixed
- Package names are moved to the same line as `name:` if there is only one package installed
- Single quotes are replaced with double quotes to maintain consistency with the rest of the code
- Changed `Lauching` to `Launching` in `tests/runtests.sh`
- The removal of the Docker container is moved to the end of the `tests/runtests.sh` script
```
Removing Docker container...
1570316059
Lauching OpenWISP tests
Error: No such container: 1570316059
Status code 200 test: fail
Error: No such container: 1570316059
```
If this is not desired, it can exit before running the tests instead:
```bash
if [ "$cleanup" = true ]; then
printf "Removing Docker container...\n"
docker rm -f $container_id
exit 0
fi
``` …
> [pip + tests] Fix Ansible deprecation warning and minor issues

- handlers/main.yml
Reload systemd only if host is running on it.
Tested on devuan linux (debian without systemd)
Fixes #131
> [bug] Reload systemd only if host have it #131

- templates/load_initial_data.py
Removed few lines from  templates/load_initial_data.py which were meant to create a default organization in favor of data migration
> [django] Removed automatic organization creation #95

- README.md
- defaults/main.yml
- tasks/pip.yml
- templates/openwisp2/settings.py
Blocked by `openwisp-network-topology release` after https://github.com/openwisp/openwisp-network-topology/issues/66
> [gsoc2020] Merged Modules remove django-netjsongraph

- tasks/pip.yml
channels_redis 3.x requires redis 5.
> [fix] Bind channels_redis to 2.4

- templates/supervisor/daphne.j2
Fixes a regression introduced in 17a9099
www-data does not have permissions to write to /run/,
hence we write this file to {{ openwisp2_path }}
> [fix] Write daphne socket file to openwisp2_path

- .travis.yml
- README.md
- defaults/main.yml
- files/generate_django_secret_key.py
- meta/main.yml
- molecule/default/converge.yml
- tasks/apt.yml
- tasks/django.yml
- tasks/django_secret_key.yml
- tasks/pip.yml
(this PR integrates the work done in #190)
- switched to use /usr/bin/python3 by default
- python-virtualenv > python3-virtualenv
- build in travis using ubuntu 20.04
- add ubuntu 20.04 (focal) to meta info
- handle redis 4/5 and dependencies
- removed step to install python-wheel (installed by pip later)
- simplified python3-virtualenv installation
- pin channels_redis to 2.4 for redis 4 compatibility
Closes #189
> [feat] Added support for Ubuntu 20.04 (#189)

- .travis.yml
- README.md
Fix molecule v3.1.1 regression: {'driver': [{'name': ['unallowed value docker']}]}
> [fix] install molecule using docker driver and updated README

- README.md
- defaults/main.yml
- molecule/resources/converge.yml
- molecule/resources/verify.yml
- tasks/complete.yml
- tasks/django.yml
- tasks/pip.yml
- tasks/supervisor.yml
- templates/openwisp2/routing.py
- templates/openwisp2/settings.py
- templates/supervisor/celerybeat.j2
Fixes #214 
--------
Blocked by:
------
I have used this playbook for manually testing this patch on Ubuntu 20.04
```
- hosts: openwisp2
become: "{{ become | default('yes') }}"
roles:
- openwisp.openwisp2
vars:
openwisp2_controller_pip: https://github.com/pandafy/openwisp-controller/tarball/fix-notification-settings
openwisp2_extra_python_packages:
- django-flat-json-widget
- https://github.com/openwisp/openwisp-notifications/tarball/master
openwisp2_default_from_email: "openwisp2@openwisp2.mydomain.com"
```
> [feature] Added support for openwisp_notifications

- README.md
- tasks/apt.yml
- tasks/django.yml
- tasks/main.yml
- tasks/ssh.yml
- templates/load_initial_data.py
A new SSH keypair will be generated if there does not exist any SSH
key pair on the machine.
The SSH key pair is used to create default access credential which
is used through a default template.
An existing template is updated if it contains configuration to
update the authorized_keys on devices.
Fixes #200
> [feature] Added automatic generation of default SSH credentials #200

- README.md
- defaults/main.yml
- molecule/resources/converge.yml
- tasks/pip.yml
- templates/openwisp2/settings.py
- templates/openwisp2/urls.py
Fixes #199
---------------
```
- hosts: openwisp2
become: "{{ become | default('yes') }}"
roles:
- openwisp.openwisp2
vars:
openwisp2_default_from_email: "openwisp2@openwisp2.mydomain.com"
openwisp2_network_topology: true
openwisp2_firmware_upgrader: true
openwisp2_firmware_upgrader_pip : "https://github.com/openwisp/openwisp-firmware-upgrader/tarball/refactor-urls"
openwisp2_controller_pip: https://github.com/openwisp/openwisp-controller/tarball/master
openwisp2_extra_python_packages:
- https://github.com/openwisp/openwisp-firmware-upgrader/tarball/refactor-urls
- https://github.com/openwisp/openwisp-controller/tarball/master  
```
------------------
**Blockers**
> [feature] Added support for openwisp-firmware-upgrader #199

- tasks/apt.yml
If the playbook is run the first time with a different DB configured
(eg: Postgis or MySQL), the geographic libraries won't be installed.
Therefore we need to install the geodjango dependencies in a step that
is separate than the installation of spatialite.
> [fix] Install geographic libraries separately

- tasks/pip.yml
This is a temporary workaround for #230.
It allows us to play safe and keep using the older dependency resolution algorithm which has been around for a long time.
We can switch to the new one in a few months.
> [change] Pin pip to 20.2.4 to avoid new dependency resolution

- files/storage.py
- tasks/django.yml
- templates/openwisp2/settings.py
Bug:
HTTP requests to fetch the marker icon were bogus due to a bug in
leaflet that made it incapable to process versioned static files
created by ManifestFilesMixin.
Fix:
- A custom static storage class with option to exclude files based on
Unix shell-style wildcards.
- PNG files are excluded from versioning
Fixes #232
> [fix] Fixed leaflet marker icon #232

- tasks/pip.yml
There's no need for this explicit install task.
The version range is defined in django-x509 and must be respected.
> [change] Removed "Install cryptography from pip"

- tasks/django.yml
- templates/load_initial_data.py
This can happen when only specific parts of the playbook are run
(eg: by running only specific tags).
> [fix] Avoid failure in load_initial_data.py if SSH vars not defined

- defaults/main.yml
- tasks/main.yml
- tasks/pip.yml
The variable `openwisp2_notifications_pip` was undefined and invalidating the `when` condition, which caused the list to not be set at all.
> [fix] Fixed bug affecting installation of custom packages

- README.md
- defaults/main.yml
- handlers/main.yml
- tasks/apt.yml
- templates/openwisp2/settings.py
Allauth Social Account app is required by allauth and can't be removed without causing errors when users are deleted.
> [fix] Revert socialaccount + minor improvements.

- README.md
I've added `openwisp2_django_loci_pip` to README.md and also moved `openwisp2_notifications_pip` after `openwisp2_controller_pip` to respect the order in which they are defined in `defaults/main.yml` file
> Document openwisp2_django_loci_pip variable in readme.

- templates/openwisp2/urls.py
django.core.urlresolvers was deprecated in Django 1.10 and removed in Django 2.0
openwisp-controller requires at least Django 3.0
> Remove deprecated django.core.urlresolvers

- .github/workflows/ci.yml
- README.md
- tasks/django.yml
Due to https://github.com/ansible-collections/community.general/issues/3215,
the CI build was failing and users were also facing problems while
using ansible-openwisp2 role.
The bug in ansible-collections/community.general has been fixed in 3.6.0,
but the idempotence test fails for the collectstatic command when
it is used. This commit also added "changed_when" condition to the 
collectstatic task.
Closes #291
> [chore] Fixed failing build #291

- .github/workflows/ci.yml
- molecule/local/molecule.yml
- tasks/apt.yml
- tasks/pip.yml
Debian Bullseye ships with redis 6, so I've added a task that installs redis 6.
Additionally I´ve had to adjust the check in `tasks/pip.yml` to make use of the newly registred variable.
The molecule tests (locally, as well as in github actions), are now also run against debian11 (again using the images by geerlingguy)
Improves on #285 
I wasn't able to reproduce the pip error mentioned in the ticket, so I didn´t change anything on these tasks
> [feature] Debian Bullseye/redis 6 support

- README.md
When you install custom pip packages, they are installed with "--no-deps" parameter, so if a custom packages requires a new package, the required package will not be installed and you have to add the dependency to "openwisp2_extra_python_packages"
> [docs] Custom OpenWISP 2 pip are installed with "--no-deps"

- README.md
- defaults/main.yml
- tasks/nginx.yml
- templates/openwisp2/settings.py
"openwisp2_firmware_upgrader_max_file_size" sets
"OPENWISP_FIRMWARE_UPGRADER_MAX_FILE_SIZE" in settings.py and
updates "client_max_body_size" in nginx config.
Closes #269
> [change] Added ansible variable to set max file size for upload #269

- README.md
- defaults/main.yml
- templates/openwisp2/settings.py
- templates/supervisor/daphne.j2
This timeout value is also used for configuring the "group_expiry"
of CHANNEL_LAYERS.
> [change] Added variable to configure daphne websocket timeout

- files/storage.py
- templates/openwisp2/urls.py
- urls.py now uses `path` instead of `url` function
- ManifestFileMixin in Django 4 also process the `sourceMap` comments. Since some dependency packages (e.g. drf-yasg) might not support Django 4 yet, updating of `CompressStaticFilesStorage` is required to get it running with with such packages. 
- Check Django 4 release note section on [django.contrib.staticfiles](https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#module-django.contrib.staticfiles)
- Check this issue in drf-yasg: https://github.com/axnsan12/drf-yasg/issues/761
- I proposed a solution to drf-yasg maintainers here: https://github.com/axnsan12/drf-yasg/commit/d9700dbf8cc80d725a7db485c2d4446c19c29840#r64030387. I will open a PR to fix this issue. 
Followed up from …
> [chores] Updated URL routes and updated CompressStaticFilesStorage backend

- README.md
Installing Jinja crashes under Python 3. Jinja2 does not crash.
> Change Jinja version

- templates/openwisp2/settings.py
DRF does not respect the settings defined in openwisp_radius.apps
if openwisp_radius is placed after djangorestframework in
INSTALLED_APPS.
> [fix] Fixed placement of "openwisp_radius" in INSTALLED_APPS

- README.md
- defaults/main.yml
- tasks/pip.yml
The aim of this backward incompatible change is to simplify the installation of custom modules, which has been very painful to achieve with the current strategy.
The custom module or alternative version can be defined in alternative to the original module, [any custom dependency will have to be defined in the dependency of the module itself using the PEP508 syntax](https://peps.python.org/pep-0508/), however, this is an advanced use case which I do not want to recommend to users, because I don't want novice people mess with the system and then come to cry for help to us when they screw it up, so I didn't add instructions on the usage of PEP508 in the README, I  think we should keep the instructions simple and good enough for general cases, advanced usage like PEP508 is still possible for …
> [change!] Simplify installation of custom modules #193

- .ansible-lint
- .github/workflows/ci.yml
- .yamllint.yml
- defaults/main.yml
- handlers/main.yml
- molecule/resources/converge.yml
- tasks/apt.yml
- tasks/django.yml
- tasks/nginx.yml
- Set `ANSIBLE_ROLES_PATH` to where roles actually installed instead of
it's `default path value` that causes **"internal-error the role 'role_name' was not found"**
Current `roles_path value` ensures roles must be installed in `same path` rather than different.
- Fixed `ansible-lint` warnings.
- Added `'fqcn-builtins'` in `.ansible-lint` because this lint rule is implicit
by default in `ansible-lint 6.x` & We need to skip this.
Closes #264
> [tests] Fixed coverage warnings in CI build #264

- README.md
After merging of https://github.com/openwisp/ansible-openwisp2/pull/381, `ansible-openwisp2/molecule/resources/converge.yml` looks like this :
https://github.com/openwisp/ansible-openwisp2/blob/b348970d49785203635562cba75a407f3b154cc2/molecule/resources/converge.yml#L25-L26
- We can now update `How to run tests` section of docs to make sure test suite run properly.
Closes #217
> [docs] Updated 'How to run tests' section #217

- templates/freeradius/openwisp_site.j2
SQL is not used for authorize and generates some warnings.
Users can still enable this if they need by setting a custom
freeradius site using the variable
"freeradius_openwisp_site_template_src".
> [change] Removed sql module from default freeradius site

- tasks/apt.yml
`is_version` returns a boolean.
Checking for string "False\n" resulted in system python3 packages not being installed
Target Host:
```
Ubuntu: 20.04
Python: 3.8.10
```
Executing Host (ansible run from):
```
ansible [core 2.13.2]
python version = 3.10.6 (main, Aug 11 2022, 13:49:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
jinja version = 3.1.2
```
Fixes #393
> [fix] Python3 (system) packages should be installed if `false` #393

- defaults/main.yml
- handlers/main.yml
- meta/main.yml
- tasks/apt.yml
- tasks/django.yml
- tasks/django_secret_key.yml
- tasks/freeradius.yml
- tasks/nginx.yml
- tasks/pip.yml
- tasks/supervisor.yml
In the interest of reducing the amount of noise generated during role tests, all bar one item that triggered linting errors have been silenced.
The remaining warning is:
```
ignore-errors: Use failed_when and specify error conditions instead of using ignore_errors.
tasks/apt.yml:51 Task/Handler: set redis to listen on ipv4
```
which I left alone because I have no context around how to trigger it / when it would error / why this ignore was introduced.
If you'd prefer this change to happen differently, please let me know.
> [chore] Task name, variable and test changes for linting

- tasks/main.yml
- tasks/system.yml
The /etc/hosts files is updated to resolve inventory_hostname to localhost (127.0.0.1).
**Blockers**
> [feature] Added task add inventory_hostname to /etc/hosts

- vars/main.yml
Bug:
The "when" condition defined in "openwisp2_default_supervisor_restart" was not getting evaluated when the task was getting executed.
Fix:
Wrapped the "when" condition in Jinja delimiters ("{{ }}"), so it is evaluated at variable assignment.
Closes https://github.com/openwisp/ansible-openwisp2/issues/406
> [fix] Fixed task for restarting supervisor services

- tasks/apt.yml
Running
$ ansible-playbook -i hosts playbook.yml -u user --check would always result in an error because the variable {{openwisp2_installed_python}} would never have been set when running with --check.
It is Ansible best practice to use Ansible native checks wherever possible and it is reasonable to assume that Ansible runs in the Python version the system has. For Python version checking, see https://serverfault.com/a/858684
Another change is to install >= Python 3.7 only if < Python 3.7 is found. The old expression looks as if it would install deadsnakes-python3.7 over system python3.7
Related to issue https://github.com/openwisp/ansible-openwisp2/issues/400
> Fix checking for Python version <3.7

- tasks/nginx.yml
The `warn` argument is causing the failure:
```
TASK [openwisp.openwisp2 : Create SSL cert if not exists yet] **********************************************************************************
fatal: [openwisp]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _uses_shell, chdir, executable, strip_empty_ends, stdin, argv, creates, _raw_params, stdin_add_newline, removes."}
```
Fixes #414
> [fix] Failure beacuse of `warn` argument

- README.md
Dependency of openwisp.influxdb/tasks/udp_mode.yml
```
ERROR! couldn't resolve module/action 'ansible.posix.sysctl'. This often indicates a misspelling, missing collection, or incorrect module path.
The error appears to be in '/home/minhnq31/.ansible/roles/openwisp.influxdb/tasks/udp_mode.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: Set net.core.rmem_max
^ here
```
> [docs] Add ansible.posix as dependency

- README.md
- defaults/main.yml
- molecule/resources/converge.yml
- tasks/consent.yml
- tasks/main.yml
- templates/openwisp2/settings.py
> [feature] Consent mechanism for clean insights measurements #452

- README.md
molecule-plugins should also be installed, otherwise may raise `CRITICAL Failed to find driver docker. Please ensure that the driver is correctly installed.` error, meet this issue when I was trying to execute `molecule test -s local` for test purpose, https://github.com/ansible/molecule/issues/920#issuecomment-1868741469
> [docs] Added molecule-plugins to "How to run tests"

- README.md
- defaults/main.yml
- templates/openwisp2/settings.py
This allows to disable celery beat tasks, useful for multi-VM deployment to avoid duplicated periodic tasks.
> [feature] Allow disabling celery beat tasks if needed

- .github/workflows/ci.yml
- README.md
- defaults/main.yml
- tasks/nginx.yml
> [fix] Include allowed_hostnames in nginx Content-Security-Policy #366

- tasks/freeradius.yml
- N/A - I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A - I have updated the documentation. 
It seems NetworkRadius have changed their public key.
> [fix] Updated freeradius PGP key

- CHANGES.md
> 24.11.0 release

- tasks/django.yml
- templates/openwisp2/__init__.py
- templates/openwisp2/version.py
This patch allows importing the version from settings.py without suffering exceptions which are caused by circular imports.
- N/A I have written new test cases for new code and/or updated existing tests for changes to existing code.
- N/A I have updated the documentation.
> [fix] Separate version to avoid circular import

- defaults/main.yml
- docs/user/role-variables.rst
- templates/nginx/site-conf.j2
Unroll the allowed network list in location admin/, as explicited in nginx docs: https://nginx.org/en/docs/http/ngx_http_access_module.html
Also adds another `openwisp2_admin_allowed_networks` variable to keep `openwisp2_admin_allowed_network` for backward compatibility.
Closes #518, #481.
This loop unrolls the value of the variable, to pass nginx config parser
> [feature] Allow restricting admin access to multiple subnets (openwisp2_admin_allowed_networks)
